// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TableTennisScoring.Models;

#nullable disable

namespace TableTennisScoring.Migrations
{
    [DbContext(typeof(TableTennisScoringContext))]
    [Migration("20250906180116_AddNewTable_MatchCompetitorAssociationTable")]
    partial class AddNewTable_MatchCompetitorAssociationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("TableTennisScoring.Models.Base.Competitor", b =>
                {
                    b.Property<int>("CompetitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompetitorFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompetitorLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompetitorNickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CompetitorId");

                    b.ToTable("Competitors");

                    b.HasData(
                        new
                        {
                            CompetitorId = 1,
                            CompetitorFirstName = "Monique",
                            CompetitorLastName = "Springer",
                            CompetitorNickname = "Monik"
                        },
                        new
                        {
                            CompetitorId = 2,
                            CompetitorFirstName = "Bob",
                            CompetitorLastName = "Jones",
                            CompetitorNickname = "Smash"
                        },
                        new
                        {
                            CompetitorId = 3,
                            CompetitorFirstName = "Alice",
                            CompetitorLastName = "Smith",
                            CompetitorNickname = "Ace"
                        });
                });

            modelBuilder.Entity("TableTennisScoring.Models.Base.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BestOfAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("MatchId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TableTennisScoring.Models.Base.MatchCompetitor", b =>
                {
                    b.Property<int>("MatchCompetitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasMaxLength(2)
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchCompetitorId");

                    b.HasIndex("CompetitorId");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchCompetitor");
                });

            modelBuilder.Entity("TableTennisScoring.Models.Base.Rule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RuleId");

                    b.ToTable("GameTypeRules");

                    b.HasData(
                        new
                        {
                            RuleId = 1,
                            RuleDescription = "The goal is to score points by hitting the ball over the net so that the opponent cannot return it legally.",
                            RuleName = "Game Objective"
                        },
                        new
                        {
                            RuleId = 2,
                            RuleDescription = "Games are typically played to 11 points, and a player must win by at least a 2-point margin.",
                            RuleName = "Scoring System"
                        },
                        new
                        {
                            RuleId = 3,
                            RuleDescription = "The serve must be made from behind the end line and the ball must bounce once on the server's side before crossing the net.",
                            RuleName = "Service Rules"
                        },
                        new
                        {
                            RuleId = 4,
                            RuleDescription = "In singles, players alternate serves every 2 points. In doubles, each player serves for 2 points in a fixed rotation.",
                            RuleName = "Serve Rotation"
                        },
                        new
                        {
                            RuleId = 5,
                            RuleDescription = "After the serve, the ball must be hit over the net and bounce once on the opponent's side. It cannot bounce more than once on your own side.",
                            RuleName = "Legal Return"
                        },
                        new
                        {
                            RuleId = 6,
                            RuleDescription = "A rally continues until a player fails to make a legal return, hits the ball off the table without touching the opponent's side, or commits a fault.",
                            RuleName = "Ball In Play"
                        },
                        new
                        {
                            RuleId = 7,
                            RuleDescription = "A let is called when the serve touches the net but still lands in the correct service box. The serve is retaken without penalty.",
                            RuleName = "Let"
                        },
                        new
                        {
                            RuleId = 8,
                            RuleDescription = "If the ball touches the net during a rally but still lands on the opponent's side, play continues.",
                            RuleName = "Ball Touching the Net During Play"
                        });
                });

            modelBuilder.Entity("TableTennisScoring.Models.Base.MatchCompetitor", b =>
                {
                    b.HasOne("TableTennisScoring.Models.Base.Competitor", "Competitor")
                        .WithMany("MatchCompetitors")
                        .HasForeignKey("CompetitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTennisScoring.Models.Base.Match", "Match")
                        .WithMany("MatchCompetitors")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competitor");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TableTennisScoring.Models.Base.Competitor", b =>
                {
                    b.Navigation("MatchCompetitors");
                });

            modelBuilder.Entity("TableTennisScoring.Models.Base.Match", b =>
                {
                    b.Navigation("MatchCompetitors");
                });
#pragma warning restore 612, 618
        }
    }
}
